---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        environment: [development,staging,pre-production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@0.8.0
    with:
      terraformPath: environments/${{ matrix.environment }}
  validate:
    strategy:
      matrix:
        environment: [development,staging,pre-production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@feat/terraformValidate
    with:
      terraformPath: environments/${{ matrix.environment }}
    needs: Lint
  plan:
    strategy:
      matrix:
        environment: [development,staging,pre-production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@0.8.0
    with:
      terraformPath: environments/${{ matrix.environment }}
    needs: [lint,validate]
