---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        environment: [development,staging,pre-production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@feat/terraform
    with:
      terraformPath: ${{ matrix.environment }}
  plan:
    strategy:
      matrix:
        environment: [development,staging,pre-production]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@feat/terraform
    with:
      terraformPath: ${{ matrix.environment }}
    needs: lint
